version: '3.1'

services:
  springboot:
    image: jorge1j/bootspring-mongo:10 
    restart: always # This will be ignored if we deploy in docker swarm
    container_name: bootspring
    environment:
    - MONGO_DB_HOSTNAME=mongo
    - MONGO_DB_USERNAME=root
    - MONGO_DB_PASSWORD=admin123
    ports:
      - 8000:8080
    working_dir: /opt/app
    depends_on:
      - mongo
    deploy:  # This will be considered only in docker swarm.
      replicas: 2
      update_config:
        parallelism: 1
        delay: 20s
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5

  mongo:
    image: mongo
    container_name: myspring-mongo
    environment:
    - MONGO_INITDB_ROOT_USERNAME=root
    - MONGO_INITDB_ROOT_PASSWORD=admin123
    volumes:
      - data:/data/db
    restart: always
    
volumes:
  data:10
    #external: true
    
networks:
  default:
    external:
      name: customoverlay
